In [2]:
import torch
import numpy as np

## Tensor 初始化

In [3]:
# tensor可以直接从数据创建，数据类型是自动推断的
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

# tensor可以从NumPy数组创建
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [4]:
# 新的tensor保留了参数tensor的属性(形状、数据类型)，除非被显式覆盖。
x_ones = torch.ones_like(x_data)# 保留x_data的属性
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)# 重写x_data的数据类型
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1582, 0.7200],
        [0.8714, 0.2982]]) 



In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9097, 0.5787, 0.2789],
        [0.7047, 0.9114, 0.4430]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor 属性

In [6]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


## Tensor 操作

转置，索引，切片，数学操作，线性代数，随机抽样等等。

In [7]:
# 将张量移动到GPU
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(f"Device of tensor: {tensor.device}")

Device of tensor: cuda:0


In [9]:
# 标准的numpy类索引和切片
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
#用torch.cat连接tensor
# 沿着给定维数连接一系列tensor
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1.shape)

# torch.stack是另一个连接tensor的操作，它与torch.cat有细微的不同
t2 = torch.stack([tensor,tensor,tensor],dim=1)
print(t2.shape)

torch.Size([4, 12])
torch.Size([4, 3, 4])


In [21]:
# 每个元素分别相乘
m1 = x_data.mul(x_data)
print(m1)

# 替代语法
m2 = x_data*x_data
print(m2)

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 1,  4],
        [ 9, 16]])


In [24]:
# 计算两个张量之间的矩阵乘法
m3 = x_data.matmul(x_data)
print(m3)

# 替代语法
m4 = x_data @ x_data
print(m4)

tensor([[ 7, 10],
        [15, 22]])
tensor([[ 7, 10],
        [15, 22]])


In [25]:
# In-place操作
# 带有_后缀的操作将tensor被替换，如x.copy_(y),x.t_()，会改变x
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Tensor与Numpy转换 

CPU和NumPy数组上的tensor可以共享它们的底层内存位置，更改其中一个将更改另一个。

In [29]:
# Tensor to NumPy array
t = torch.ones(5)
print('t =',t)
n = t.numpy()
print('n =',n)

# tensor的变化反映在NumPy数组中
t.add_(1)
print('t =',t)
print('n =',n)

t = tensor([1., 1., 1., 1., 1.])
n = [1. 1. 1. 1. 1.]
t = tensor([2., 2., 2., 2., 2.])
n = [2. 2. 2. 2. 2.]


In [30]:
# NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)
print('n =',n)
print('t =',t)

np.add(n,1,out=n)
print('n =',n)
print('t =',t)

n = [1. 1. 1. 1. 1.]
t = tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n = [2. 2. 2. 2. 2.]
t = tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
